## Import libraries

In [68]:
import pandas as pd
import numpy as np

## Import the dataset

In [3]:
train = pd.read_csv('input/ford_train.csv')
test = pd.read_csv('input/ford_test.csv')
solution = pd.read_csv('input/solution.csv')

In [4]:
train.head()

TrialID  ObsNum  IsAlert       P1        P2    P3       P4        P5   P6  \
0        0       0        0  34.7406   9.84593  1400  42.8571  0.290601  572   
1        0       1        0  34.4215  13.41120  1400  42.8571  0.290601  572   
2        0       2        0  34.3447  15.18520  1400  42.8571  0.290601  576   
3        0       3        0  34.3421   8.84696  1400  42.8571  0.290601  576   
4        0       4        0  34.3322  14.69940  1400  42.8571  0.290601  576   

        P7   ...        V2   V3       V4  V5    V6  V7    V8  V9  V10      V11  
0  104.895   ...     0.175  752  5.99375   0  2005   0  13.4   0    4  14.8004  
1  104.895   ...     0.455  752  5.99375   0  2007   0  13.4   0    4  14.7729  
2  104.167   ...     0.280  752  5.99375   0  2011   0  13.4   0    4  14.7736  
3  104.167   ...     0.070  752  5.99375   0  2015   0  13.4   0    4  14.7667  
4  104.167   ...     0.175  752  5.99375   0  2017   0  13.4   0    4  14.7757  

[5 rows x 33 columns]

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604329 entries, 0 to 604328
Data columns (total 33 columns):
TrialID    604329 non-null int64
ObsNum     604329 non-null int64
IsAlert    604329 non-null int64
P1         604329 non-null float64
P2         604329 non-null float64
P3         604329 non-null int64
P4         604329 non-null float64
P5         604329 non-null float64
P6         604329 non-null int64
P7         604329 non-null float64
P8         604329 non-null int64
E1         604329 non-null float64
E2         604329 non-null float64
E3         604329 non-null int64
E4         604329 non-null int64
E5         604329 non-null float64
E6         604329 non-null int64
E7         604329 non-null int64
E8         604329 non-null int64
E9         604329 non-null int64
E10        604329 non-null int64
E11        604329 non-null float64
V1         604329 non-null float64
V2         604329 non-null float64
V3         604329 non-null int64
V4         604329 non-null float64
V5     

In [67]:
train.describe()

TrialID         ObsNum        IsAlert             P1  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean      250.167657     603.841765       0.578799      35.449020   
std       145.446164     348.931601       0.493752       7.484629   
min         0.000000       0.000000       0.000000     -22.481200   
25%       125.000000     302.000000       0.000000      31.758100   
50%       250.000000     604.000000       1.000000      34.145100   
75%       374.000000     906.000000       1.000000      37.311900   
max       510.000000    1210.000000       1.000000     101.351000   

                  P2             P3             P4             P5  \
count  604329.000000  604329.000000  604329.000000  604329.000000   
mean       11.996525    1026.671035      64.061965       0.178923   
std         3.760292     309.277877      19.755950       0.372309   
min       -45.629200     504.000000      23.885300       0.038920   
25%         9.903540     792.000000      49.180300       0.092110   
50%        11.400400    1000.000000      60.000000       0.105083   
75%        13.644200    1220.000000      75.757600       0.138814   
max        71.173700    2512.000000     119.048000      27.202200   

                  P6             P7      ...                   V2  \
count  604329.000000  604329.000000      ...        604329.000000   
mean      845.384610      77.887628      ...            -0.037710   
std      2505.335141      18.577930      ...             0.403896   
min       128.000000       0.262224      ...            -4.795000   
25%       668.000000      66.666700      ...            -0.175000   
50%       800.000000      75.000000      ...             0.000000   
75%       900.000000      89.820400      ...             0.070000   
max    228812.000000     468.750000      ...             3.990000   

                  V3             V4             V5             V6        V7  \
count  604329.000000  604329.000000  604329.000000  604329.000000  604329.0   
mean      573.786433      19.961030       0.179814    1715.688383       0.0   
std       298.412888      63.269456       0.384033     618.176470       0.0   
min       240.000000       0.000000       0.000000       0.000000       0.0   
25%       255.000000       1.487500       0.000000    1259.000000       0.0   
50%       511.000000       3.018750       0.000000    1994.000000       0.0   
75%       767.000000       7.481250       0.000000    2146.000000       0.0   
max      1023.000000     484.488000       1.000000    4892.000000       0.0   

                  V8        V9            V10            V11  
count  604329.000000  604329.0  604329.000000  604329.000000  
mean       12.710354       0.0       3.312257      11.668277  
std        11.532085       0.0       1.243586       9.934423  
min         0.000000       0.0       1.000000       1.676730  
25%         0.000000       0.0       3.000000       7.947680  
50%        12.800000       0.0       4.000000      10.772600  
75%        21.900000       0.0       4.000000      15.270900  
max        82.100000       0.0       7.000000     262.534000  

[8 rows x 33 columns]

## Feature scaling

In [23]:
from sklearn.preprocessing import StandardScaler

In [33]:
train_data_to_scale = train.drop('IsAlert', axis=1)
test_data_to_scale = test.drop('IsAlert', axis=1)

scaler = StandardScaler()
scaler.fit(train_data_to_scale)

StandardScaler(copy=True, with_mean=True, with_std=True)

## Training data and testing data

In [69]:
X_train = pd.DataFrame(data=scaler.transform(train_data_to_scale), columns=train_data_to_scale.columns)
X_test = pd.DataFrame(data=scaler.transform(test_data_to_scale), columns=test_data_to_scale.columns)

y_train = train['IsAlert']
y_test = test['IsAlert']

## Decision tree classifier

In [36]:
# Decision tree
from sklearn.tree import DecisionTreeClassifier

In [37]:
dtree = DecisionTreeClassifier()

In [48]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

## Testing the tree

In [74]:
preds = dtree.predict(X_test)

In [75]:
preds

array([1, 1, 1, ..., 1, 1, 1])

## Evaluating the tree

In [76]:
from sklearn.metrics import classification_report, confusion_matrix

In [77]:
print(classification_report(solution['Prediction'], preds))

             precision    recall  f1-score   support

          0       0.38      0.69      0.49     29914
          1       0.86      0.63      0.73     90926

avg / total       0.74      0.64      0.67    120840



In [78]:
print(confusion_matrix(solution['Prediction'], preds))

[[20518  9396]
 [33646 57280]]


## Random forest classifier

In [53]:
# Random forest
from sklearn.ensemble import RandomForestClassifier

In [62]:
rfc = RandomForestClassifier(n_estimators=100)

In [63]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

## Testing the forest

In [80]:
preds = rfc.predict(X_test)

## Evaluating the forest

In [65]:
print(classification_report(solution['Prediction'], preds))

             precision    recall  f1-score   support

          0       0.99      0.53      0.69     29914
          1       0.87      1.00      0.93     90926

avg / total       0.90      0.88      0.87    120840



In [66]:
print(confusion_matrix(solution['Prediction'], preds))

[[15823 14091]
 [  207 90719]]
